#!/usr/bin/env bash
# load-config.sh — Template config/xeon.yaml from environment variables.
#
# Usage:
#   BACKEND_LITELLM_URL=http://host.docker.internal:4000 \
#   REDIS_URL=redis://admission-scheduler-redis:6379/0 \
#   LOG_DIR=/var/log/scheduler \
#   ./scripts/load-config.sh [output_path]
#
# If output_path is omitted, overwrites config/xeon.yaml in-place.
# Requires: envsubst (part of gettext, installed via 'brew install gettext'
#           or 'apt-get install gettext-base').

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TEMPLATE="${REPO_ROOT}/config/xeon.yaml"
OUTPUT="${1:-${TEMPLATE}}"

# ---- defaults (used when env var is not set) ----
export BACKEND_LITELLM_URL="${BACKEND_LITELLM_URL:-http://host.docker.internal:4000}"
export REDIS_URL="${REDIS_URL:-redis://admission-scheduler-redis:6379/0}"
export LOG_DIR="${LOG_DIR:-/var/log/scheduler}"
export WORKER_POLL_TIMEOUT="${WORKER_POLL_TIMEOUT:-5}"
export LEASE_WATCHER_INTERVAL="${LEASE_WATCHER_INTERVAL:-10}"
export INTEGRITY_CHECK_INTERVAL="${INTEGRITY_CHECK_INTERVAL:-60}"

# ---- sanity check ----
if ! command -v envsubst &> /dev/null; then
  echo "ERROR: envsubst not found." >&2
  echo "  macOS: brew install gettext && brew link gettext --force" >&2
  echo "  Linux: apt-get install gettext-base" >&2
  exit 1
fi

# ---- read the YAML template and substitute ----
# We build a small inline template from the canonical xeon.yaml shape
# rather than embedding $-tokens in the committed YAML (which would break
# plain 'cat' inspection).  Operators can extend this template block.

RENDERED=$(cat <<YAML_TEMPLATE
# Generated by scripts/load-config.sh — do not hand-edit.
# Source env: BACKEND_LITELLM_URL, REDIS_URL, LOG_DIR, WORKER_POLL_TIMEOUT,
#             LEASE_WATCHER_INTERVAL, INTEGRITY_CHECK_INTERVAL
scheduler:
  redis_url: "${REDIS_URL}"
  backend_litellm_url: "${BACKEND_LITELLM_URL}"
  worker_poll_timeout_seconds: ${WORKER_POLL_TIMEOUT}
  lease_watcher_interval_seconds: ${LEASE_WATCHER_INTERVAL}
  integrity_check_interval_seconds: ${INTEGRITY_CHECK_INTERVAL}
  log_dir: "${LOG_DIR}"
  log_rotate_utc_midnight: true

defaults:
  max_concurrency: 3
  max_queue_depth: 50
  max_wait_seconds: 120
  sync_timeout_seconds: 120
  priority: 5
  fallback_policy:
    enabled: false

models:
  code:
    max_concurrency: 2
    max_queue_depth: 20
    max_wait_seconds: 180
    sync_timeout_seconds: 300
    priority: 3
  chat-fast:
    max_concurrency: 4
    max_queue_depth: 40
    max_wait_seconds: 60
    sync_timeout_seconds: 120
    priority: 5
  brain-exec:
    max_concurrency: 1
    max_queue_depth: 5
    max_wait_seconds: 300
    sync_timeout_seconds: 600
    priority: 3
  tool-worker:
    max_concurrency: 6
    max_queue_depth: 100
    max_wait_seconds: 30
    sync_timeout_seconds: 60
    priority: 5
YAML_TEMPLATE
)

echo "$RENDERED" | envsubst > "$OUTPUT"

echo "Wrote config to: $OUTPUT"
echo "  BACKEND_LITELLM_URL = $BACKEND_LITELLM_URL"
echo "  REDIS_URL           = $REDIS_URL"
echo "  LOG_DIR             = $LOG_DIR"
